name: 'build'
on: [ 'pull_request', 'push' ]
jobs:
    build:
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: 'ubuntu-latest'
        steps:
            -   name: 'checkout repo'
                uses: 'actions/checkout@v2'
            -   name: 'setup JDK'
                uses: 'actions/setup-java@v1'
                with:
                    java-version: 8
            -   name: 'mongo'
                uses: supercharge/mongodb-github-action@1.7.0
                with:
                    mongodb-version: '5.0'
            -   name: 'build'
                run: './gradlew build'